#######################
# Bare minimum config #
#######################

esphome:
    name: vue-utility
    platform: ESP32
    board: esp-wrover-kit
    includes:
        - emporia_vue_utility.h

# Add your own wifi credentials
wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password

ota:

logger:

api:

# This uart connects to the MGM111
uart:
    id: emporia_uart
    rx_pin: GPIO21
    tx_pin: GPIO22
    baud_rate: 115200

sensor:
    - platform: custom
      lambda: |-
        auto vue = new EmporiaVueUtility(id(emporia_uart));
        App.register_component(vue);
        return {vue->kWh, vue->W};
      sensors:
          - name: "kWh"
            id: kwh
          - name: "Watts"
            id: watts

